url: https://y7kim.github.io
baseurl: /  #/EtherCISwebsite/  # /jekylltheme2/  /agency-jekyll-theme/

include: ["_pages"]

# Site settings
title: EtherCIS
company: ADOC Software Development
title2: EtherCIS
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ethercis

# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty
